# Generated by Django 5.1.5 on 2025-02-05 02:37

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="images/profile-alt.png",
                null=True,
                upload_to="profile_pictures/",
                validators=[users.utils.validate_image_size],
            ),
        ),
    ]
