# Generated by Django 5.1.5 on 2025-02-07 13:39

import django.db.models.deletion
import users.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_es", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
                (
                    "rental_price_per_day",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="equipment_images/",
                        validators=[users.utils.validate_image_size],
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("Good", "Good"), ("Fair", "Fair"), ("Poor", "Poor")],
                        default="Good",
                        max_length=50,
                    ),
                ),
                ("available_quantity", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_es", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="Beginner",
                        max_length=50,
                    ),
                ),
                (
                    "best_season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Spring", "Spring"),
                            ("Summer", "Summer"),
                            ("Autumn", "Autumn"),
                            ("Winter", "Winter"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarineLife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("name_en", models.CharField(max_length=50, null=True, unique=True)),
                ("name_es", models.CharField(max_length=50, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="marine_life_images/",
                        validators=[users.utils.validate_image_size],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DivingTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_es", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_es", models.TextField(null=True)),
                ("date", models.DateField()),
                ("duration_days", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("available_spots", models.PositiveIntegerField()),
                (
                    "instructor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instructed_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="trips.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("num_people", models.PositiveIntegerField(default=1)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=8),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Pending", "Pending")],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="trips.divingtrip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentRental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rental_days", models.PositiveIntegerField(default=1)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=8),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to="trips.equipment",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to="trips.divingtrip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="marine_life",
            field=models.ManyToManyField(blank=True, to="trips.marinelife"),
        ),
        migrations.CreateModel(
            name="TripImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="trip_images/",
                        validators=[users.utils.validate_image_size],
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("caption_en", models.CharField(blank=True, max_length=255, null=True)),
                ("caption_es", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="trips.divingtrip",
                    ),
                ),
            ],
        ),
    ]
